name: build

on:
  workflow_call:
    inputs:
      version:
        description: 'Build for specific mod version'
        required: false
        type: string
        default: 'v1.1'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build release files
        env:
          GITHUB_REF_NAME: ${{ inputs.version }}
        run: bash ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
