on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: ./github/workflows/build.yml
        with:
          version: ${{ github.ref_name }}
      - name: Publish release files (Fabric)
        uses: Kir-Antipov/mc-publish@4db8bd126f74d5e143822181a2b1201308e2c796
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: 2XONb5Wh
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 898576
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}

          java: |
            17

